server:
  listen_address: 'localhost'
  port: 8080
  enable_ssl: true

routes:
  - name: "auth"
    prefix: "/auth"
    location: "http://localhost:8081/auth"

  - name: "service1"
    prefix: "/service1"
    location: "http://localhost:8082/service1"